AY2425S2-CS2103T-T17-3/tp

- docs/AboutUs.md
> Add Zhan Hong's info in About Us page

- README.md
> Update link of build status badge

- README.md
> Acknowledge original source of code

- docs/_config.yml
- docs/_sass/minima/_base.scss
> Update top navigation bar of project website

- docs/DeveloperGuide.md
> Update target profile and value proposition

- docs/DeveloperGuide.md
> Update DG with use cases

- README.md
> Update README to align with project

- docs/AboutUs.md
- docs/DevOps.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/index.md
> Update docs to align with project

- docs/DeveloperGuide.md
> Update glossary with relevant terms to Tutorly

- src/main/java/tutorly/logic/Messages.java
- src/main/java/tutorly/logic/commands/AddCommand.java
- src/main/java/tutorly/logic/commands/EditCommand.java
- src/main/java/tutorly/logic/parser/AddCommandParser.java
- src/main/java/tutorly/logic/parser/CliSyntax.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/model/person/Memo.java
- src/main/java/tutorly/model/person/Person.java
- src/main/java/tutorly/model/util/SampleDataUtil.java
- src/main/java/tutorly/storage/JsonAdaptedPerson.java
- src/main/java/tutorly/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/tutorly/logic/commands/EditPersonDescriptorTest.java
- src/test/java/tutorly/model/person/PersonTest.java
- src/test/java/tutorly/storage/JsonAdaptedPersonTest.java
- src/test/java/tutorly/testutil/PersonBuilder.java
> Create new memo field for Student

- src/main/java/tutorly/model/Session.java
- src/test/java/tutorly/model/SessionTest.java
> Create Session class

- src/main/java/tutorly/logic/commands/DeleteCommand.java
- src/main/java/tutorly/model/AddressBook.java
> Add archive feature to delete command

- src/main/java/tutorly/model/AddressBook.java
- src/main/java/tutorly/model/person/Person.java
- src/main/java/tutorly/model/person/UniquePersonList.java
- src/test/java/tutorly/logic/LogicManagerTest.java
- src/test/java/tutorly/logic/commands/EditCommandTest.java
- src/test/java/tutorly/model/person/PersonTest.java
> Assign student ID for every new student added

- src/main/java/tutorly/commons/util/StringUtil.java
- src/main/java/tutorly/logic/commands/SearchCommand.java
- src/test/java/tutorly/commons/util/StringUtilTest.java
> Relax search command to allow partial match

- src/main/java/tutorly/model/attendancerecord/AttendanceRecord.java
- src/test/java/tutorly/model/attendancerecord/AttendanceRecordTest.java
> Add session student class

- src/main/java/tutorly/model/person/Person.java
- src/main/java/tutorly/storage/JsonAdaptedPerson.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/tutorly/storage/JsonAdaptedPersonTest.java
- src/test/java/tutorly/testutil/PersonBuilder.java
- src/test/java/tutorly/testutil/TypicalPersons.java
> Persist student ID

- src/main/java/tutorly/logic/commands/SearchCommand.java
- src/main/java/tutorly/logic/parser/SearchCommandParser.java
- src/main/java/tutorly/model/person/PhoneContainsKeywordsPredicate.java
- src/main/java/tutorly/model/person/PredicateFilter.java
- src/test/java/tutorly/logic/commands/SearchCommandTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/logic/parser/SearchCommandParserTest.java
- src/test/java/tutorly/model/person/PhoneContainsKeywordsPredicateTest.java
- src/test/java/tutorly/model/person/PredicateFilterTest.java
Closes #87 
- Add new PredicateFilter class for combining of multiple predicates for filtered person list
- Add PhoneContainsKeywordsPredicateClass
- Allow optional prefix name and phone keywords for search command
> Add search by phone field

- src/main/java/tutorly/model/session/Session.java
- src/main/java/tutorly/storage/JsonAdaptedSession.java
- src/main/java/tutorly/storage/JsonSerializableAddressBook.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/tutorly/model/session/SessionTest.java
- src/test/java/tutorly/storage/JsonAdaptedSessionTest.java
> Persist sessions

- src/main/java/tutorly/model/person/Person.java
- src/main/java/tutorly/storage/JsonAdaptedPerson.java
- src/main/java/tutorly/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/tutorly/storage/JsonAdaptedPersonTest.java
> Display student ID in Person fields

- src/main/java/tutorly/logic/commands/SearchCommand.java
- src/main/java/tutorly/logic/parser/CliSyntax.java
- src/main/java/tutorly/logic/parser/SearchCommandParser.java
- src/main/java/tutorly/model/person/AttendSessionPredicate.java
- src/main/java/tutorly/model/person/PredicateFilter.java
- src/test/java/tutorly/logic/commands/SearchCommandTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/model/person/AttendSessionPredicateTest.java
- src/test/java/tutorly/model/person/PredicateFilterTest.java
> Search for students attending a session

- build.gradle
> Enable assertions in gradle build file

- src/main/java/tutorly/logic/commands/AssignStudentCommand.java
- src/main/java/tutorly/model/Model.java
- src/main/java/tutorly/model/ModelManager.java
- src/test/java/tutorly/logic/commands/AssignStudentCommandTest.java
- src/test/java/tutorly/logic/commands/CreateSessionCommandTest.java
- src/test/java/tutorly/model/ModelManagerTest.java
Closes #75 
Parser will be added in a future PR.
> Add assign student command

- src/main/java/tutorly/logic/commands/EditStudentCommand.java
- src/main/java/tutorly/logic/parser/EditCommandParser.java
- src/main/java/tutorly/model/person/Identity.java
- src/main/java/tutorly/model/person/Name.java
- src/test/java/tutorly/logic/commands/EditStudentCommandTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/logic/parser/EditCommandParserTest.java
- src/test/java/tutorly/model/person/NameTest.java
- src/test/java/tutorly/testutil/TypicalIdentities.java
> Migrate edit command to use student ID or name

- src/main/java/tutorly/model/attendancerecord/AttendanceRecord.java
- src/test/java/tutorly/model/attendancerecord/AttendanceRecordTest.java
> Add comment field

- src/main/java/tutorly/logic/Messages.java
- src/main/java/tutorly/logic/commands/AddStudentCommand.java
- src/main/java/tutorly/logic/commands/DeleteStudentCommand.java
- src/main/java/tutorly/logic/commands/EditStudentCommand.java
- src/main/java/tutorly/logic/commands/RestoreStudentCommand.java
- src/main/java/tutorly/logic/parser/RestoreCommandParser.java
- src/main/java/tutorly/model/AddressBook.java
- src/main/java/tutorly/model/Model.java
- src/main/java/tutorly/model/ModelManager.java
- src/main/java/tutorly/model/person/Identity.java
- src/main/java/tutorly/ui/PersonCard.java
- src/test/java/tutorly/logic/commands/AddSessionCommandTest.java
- src/test/java/tutorly/logic/commands/AddStudentCommandIntegrationTest.java
- src/test/java/tutorly/logic/commands/AddStudentCommandTest.java
- src/test/java/tutorly/logic/commands/AssignStudentCommandTest.java
- src/test/java/tutorly/logic/commands/EditStudentCommandTest.java
- src/test/java/tutorly/logic/commands/RestoreStudentCommandTest.java
- src/test/java/tutorly/logic/parser/RestoreCommandParserTest.java
- src/test/java/tutorly/model/AddressBookTest.java
> Migrate restore command to use student ID or name

- src/main/java/tutorly/logic/parser/AddSessionCommandParser.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/test/java/tutorly/logic/parser/AddSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
> Set up AddSessionCommandParser

- src/main/java/tutorly/logic/parser/AddSessionCommandParser.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/model/AddressBook.java
- src/test/java/tutorly/logic/parser/AddSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/model/AddressBookTest.java
> Auto set session id after added to Addressbook

- src/main/java/tutorly/model/AddressBook.java
- src/main/java/tutorly/model/ReadOnlyAddressBook.java
- src/main/java/tutorly/model/uniquelist/UniqueList.java
- src/main/java/tutorly/storage/JsonSerializableAddressBook.java
- src/test/java/tutorly/model/AddressBookTest.java
> Add running counter of student and session IDs

- src/main/java/tutorly/logic/commands/SearchSessionCommand.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/logic/parser/SearchSessionCommandParser.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/model/filter/DateSessionFilter.java
- src/main/java/tutorly/model/filter/SubjectContainsKeywordsFilter.java
- src/test/java/tutorly/logic/commands/CommandTestUtil.java
- src/test/java/tutorly/logic/commands/SearchSessionCommandTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/logic/parser/SearchCommandParserTest.java
- src/test/java/tutorly/logic/parser/SearchSessionCommandParserTest.java
- src/test/java/tutorly/model/filter/DateSessionFilterTest.java
- src/test/java/tutorly/model/filter/SubjectContainsKeywordsFilterTest.java
> Add search session command

- src/main/java/tutorly/ui/HelpWindow.java
> Update help message link to UG

- src/main/java/tutorly/logic/commands/DeleteStudentCommand.java
- src/main/java/tutorly/logic/commands/EditStudentCommand.java
- src/main/java/tutorly/logic/commands/RestoreStudentCommand.java
- src/main/java/tutorly/logic/parser/AddSessionCommandParser.java
- src/main/java/tutorly/logic/parser/AddStudentCommandParser.java
- src/main/java/tutorly/logic/parser/CliSyntax.java
- src/main/java/tutorly/logic/parser/DeleteStudentCommandParser.java
- src/main/java/tutorly/logic/parser/EditStudentCommandParser.java
- src/main/java/tutorly/logic/parser/EnrolSessionCommandParser.java
- src/main/java/tutorly/logic/parser/RestoreStudentCommandParser.java
- src/main/java/tutorly/logic/parser/SearchStudentCommandParser.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/logic/parser/StudentCommandParser.java
- src/test/java/tutorly/logic/commands/CommandTestUtil.java
- src/test/java/tutorly/logic/parser/AddStudentCommandParserTest.java
- src/test/java/tutorly/logic/parser/DeleteStudentCommandParserTest.java
- src/test/java/tutorly/logic/parser/EditStudentCommandParserTest.java
- src/test/java/tutorly/logic/parser/EnrolSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/RestoreStudentCommandParserTest.java
- src/test/java/tutorly/logic/parser/SearchStudentCommandParserTest.java
> Remove unused ID prefix

- src/main/java/tutorly/logic/commands/DeleteStudentCommand.java
- src/main/java/tutorly/logic/commands/EditStudentCommand.java
- src/main/java/tutorly/logic/commands/EnrolSessionCommand.java
- src/main/java/tutorly/logic/commands/RestoreStudentCommand.java
- src/main/java/tutorly/model/Model.java
- src/main/java/tutorly/model/ModelManager.java
- src/main/java/tutorly/model/person/Identity.java
- src/test/java/tutorly/logic/commands/AddSessionCommandTest.java
- src/test/java/tutorly/logic/commands/AddStudentCommandTest.java
- src/test/java/tutorly/logic/commands/DeleteStudentCommandTest.java
- src/test/java/tutorly/model/ModelManagerTest.java
- src/test/java/tutorly/model/person/IdentityTest.java
> Refactor identity getPerson logic to model

- src/main/java/tutorly/logic/commands/ListSessionCommand.java
- src/main/java/tutorly/logic/commands/UnenrolSessionCommand.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/model/Model.java
- src/test/java/tutorly/logic/commands/ListSessionCommandTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
> Add List Sessions command

- src/main/java/tutorly/logic/commands/DeleteSessionCommand.java
- src/main/java/tutorly/logic/parser/DeleteSessionCommandParser.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/model/Model.java
- src/main/java/tutorly/model/ModelManager.java
- src/test/java/tutorly/logic/commands/AddSessionCommandTest.java
- src/test/java/tutorly/logic/commands/AddStudentCommandTest.java
- src/test/java/tutorly/logic/commands/DeleteSessionCommandTest.java
- src/test/java/tutorly/logic/parser/DeleteSessionCommandParserTest.java
> Implement session delete feature

- src/main/java/tutorly/logic/commands/AttendanceMarkSessionCommand.java
- src/main/java/tutorly/logic/commands/AttendanceUnmarkSessionCommand.java
- src/main/java/tutorly/logic/commands/UnenrolSessionCommand.java
- src/main/java/tutorly/logic/parser/AttendanceMarkSessionCommandParser.java
- src/main/java/tutorly/logic/parser/AttendanceUnmarkSessionCommandParser.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/model/AddressBook.java
- src/main/java/tutorly/model/Model.java
- src/main/java/tutorly/model/ModelManager.java
- src/main/java/tutorly/model/attendancerecord/UniqueAttendanceRecordList.java
- src/main/java/tutorly/model/person/UniquePersonList.java
- src/main/java/tutorly/model/session/UniqueSessionList.java
- src/main/java/tutorly/model/uniquelist/UniqueList.java
- src/test/java/tutorly/logic/commands/AddSessionCommandTest.java
- src/test/java/tutorly/logic/commands/AddStudentCommandTest.java
- src/test/java/tutorly/logic/commands/AttendanceMarkSessionCommandTest.java
- src/test/java/tutorly/logic/commands/AttendanceUnmarkSessionCommandTest.java
- src/test/java/tutorly/logic/parser/AttendanceMarkSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/AttendanceUnmarkSessionCommandParserTest.java
- src/test/java/tutorly/model/attendancerecord/UniqueAttendanceRecordListTest.java
This PR implements Mark and Unmark commands, as well as their respective parsers.
Closes #133, closes #134.
> Add Attendance Mark and Unmark commands

- src/main/java/tutorly/model/session/Session.java
- src/test/java/tutorly/model/session/UniqueSessionListTest.java
> Remove id equality check when comparing sessions

- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
> Extend timeslot to include optional end date

- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
> Multiple intermediate spaces in names and addresses should be collapsed to one

- src/main/resources/view/ResultDisplay.fxml
> Update ResultDisplay to wrap text

- src/main/java/tutorly/logic/parser/AddressBookParser.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/logic/parser/StudentCommandParser.java
> Allow case insensitive commands

- src/main/java/tutorly/logic/Messages.java
- src/main/java/tutorly/ui/SessionCard.java
- src/main/resources/view/SessionListCard.fxml
- src/test/java/tutorly/logic/MessagesTest.java
> Format timeslot into human readable string

- src/main/java/tutorly/model/util/SampleDataUtil.java
- src/test/java/tutorly/util/SampleDataUtilTest.java
> Add contextualized sample data

- src/main/java/tutorly/logic/commands/AddSessionCommand.java
- src/main/java/tutorly/logic/commands/AddStudentCommand.java
- src/main/java/tutorly/logic/commands/AttendanceMarkSessionCommand.java
- src/main/java/tutorly/logic/commands/AttendanceUnmarkSessionCommand.java
- src/main/java/tutorly/logic/commands/DeleteSessionCommand.java
- src/main/java/tutorly/logic/commands/DeleteStudentCommand.java
- src/main/java/tutorly/logic/commands/EditStudentCommand.java
- src/main/java/tutorly/logic/commands/EnrolSessionCommand.java
- src/main/java/tutorly/logic/commands/HelpCommand.java
- src/main/java/tutorly/logic/commands/SearchSessionCommand.java
- src/main/java/tutorly/logic/commands/SearchStudentCommand.java
- src/main/java/tutorly/logic/commands/UnenrolSessionCommand.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/model/person/Address.java
- src/main/java/tutorly/model/person/Email.java
- src/main/java/tutorly/model/person/Identity.java
- src/main/java/tutorly/model/person/Memo.java
- src/main/java/tutorly/model/person/Name.java
- src/main/java/tutorly/model/person/Phone.java
- src/main/java/tutorly/model/tag/Tag.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
- src/test/java/tutorly/model/person/AddressTest.java
- src/test/java/tutorly/model/person/EmailTest.java
- src/test/java/tutorly/model/person/MemoTest.java
- src/test/java/tutorly/model/person/NameTest.java
- src/test/java/tutorly/model/person/PhoneTest.java
- src/test/java/tutorly/model/tag/TagTest.java
> Add length validation for user inputs

- src/main/java/tutorly/ui/AttendanceRecordCard.java
- src/main/resources/view/AttendanceRecordListCard.fxml
> Add student id to attendance record card

- src/main/java/tutorly/logic/commands/AddSessionCommand.java
- src/main/java/tutorly/logic/commands/AddStudentCommand.java
- src/main/java/tutorly/logic/commands/AttendanceMarkSessionCommand.java
- src/main/java/tutorly/logic/commands/AttendanceUnmarkSessionCommand.java
- src/main/java/tutorly/logic/commands/DeleteSessionCommand.java
- src/main/java/tutorly/logic/commands/DeleteStudentCommand.java
- src/main/java/tutorly/logic/commands/EditSessionCommand.java
- src/main/java/tutorly/logic/commands/EditStudentCommand.java
- src/main/java/tutorly/logic/commands/EnrolSessionCommand.java
- src/main/java/tutorly/logic/commands/ListSessionCommand.java
- src/main/java/tutorly/logic/commands/ListStudentCommand.java
- src/main/java/tutorly/logic/commands/SearchSessionCommand.java
- src/main/java/tutorly/logic/commands/SearchStudentCommand.java
- src/main/java/tutorly/logic/commands/SessionCommand.java
- src/main/java/tutorly/logic/commands/StudentCommand.java
- src/main/java/tutorly/logic/commands/UnenrolSessionCommand.java
- src/main/java/tutorly/ui/ListPanel.java
- src/main/java/tutorly/ui/MainWindow.java
- src/main/java/tutorly/ui/Tab.java
- src/test/java/tutorly/logic/commands/CommandResultTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/testutil/EditSessionDescriptorBuilder.java
- src/test/java/tutorly/testutil/SessionBuilder.java
- src/test/java/tutorly/testutil/SessionUtil.java
> Add auto selection of Students, Sessions, and Attendance Records

- src/main/java/tutorly/model/person/Name.java
- src/test/java/tutorly/model/person/PersonTest.java
> Make person names case-insensitive

- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/model/person/Name.java
> Session timestamp should be case insensitive

- src/main/java/tutorly/logic/commands/AttendanceMarkSessionCommand.java
- src/main/java/tutorly/logic/commands/AttendanceUnmarkSessionCommand.java
Resolves  #234 , resolves #235
> Fix usage message formatting

- src/main/java/tutorly/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
> Add command summary to help window

- src/main/java/tutorly/model/person/Address.java
- src/main/java/tutorly/model/person/Email.java
- src/main/java/tutorly/model/person/Memo.java
- src/main/java/tutorly/model/person/Name.java
- src/main/java/tutorly/model/person/Phone.java
- src/main/java/tutorly/model/session/Subject.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
- src/test/java/tutorly/model/person/AddressTest.java
- src/test/java/tutorly/model/person/NameTest.java
- src/test/java/tutorly/model/person/PhoneTest.java
- src/test/java/tutorly/storage/JsonAdaptedPersonTest.java
> Resolve overzealous input blocking

- src/main/java/tutorly/logic/commands/AddSessionCommand.java
- src/main/java/tutorly/logic/commands/AddStudentCommand.java
- src/main/java/tutorly/model/AddressBook.java
- src/main/java/tutorly/storage/JsonSerializableAddressBook.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicateSessionAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidNextPersonIdAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidNextSessionIdAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/java/tutorly/model/AddressBookTest.java
- src/test/java/tutorly/storage/JsonSerializableAddressBookTest.java
- src/test/java/tutorly/testutil/TypicalAddressBook.java
> Add ID validation during deserialisation

- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/test/java/tutorly/logic/MessagesTest.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
> Allow optional leading zero for date and time

- src/main/java/tutorly/logic/commands/AttendanceFeedbackCommand.java
- src/main/java/tutorly/logic/commands/AttendanceMarkSessionCommand.java
- src/main/java/tutorly/logic/commands/AttendanceUnmarkSessionCommand.java
- src/main/java/tutorly/logic/commands/EditSessionCommand.java
- src/main/java/tutorly/logic/commands/EnrolSessionCommand.java
- src/main/java/tutorly/logic/commands/UnenrolSessionCommand.java
- src/main/java/tutorly/logic/parser/AttendanceFeedbackCommandParser.java
- src/main/java/tutorly/logic/parser/CliSyntax.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/model/attendancerecord/AttendanceRecord.java
- src/main/java/tutorly/model/attendancerecord/Feedback.java
- src/main/java/tutorly/model/util/SampleDataUtil.java
- src/main/java/tutorly/storage/JsonAdaptedAttendanceRecord.java
- src/test/java/tutorly/logic/commands/AttendanceFeedbackCommandTest.java
- src/test/java/tutorly/logic/commands/AttendanceMarkSessionCommandTest.java
- src/test/java/tutorly/logic/commands/AttendanceUnmarkSessionCommandTest.java
- src/test/java/tutorly/logic/commands/CommandTestUtil.java
- src/test/java/tutorly/logic/commands/EnrolSessionCommandTest.java
- src/test/java/tutorly/logic/parser/AddressBookParserTest.java
- src/test/java/tutorly/logic/parser/AttendanceFeedbackCommandParserTest.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
- src/test/java/tutorly/model/AddressBookTest.java
- src/test/java/tutorly/model/attendancerecord/AttendanceRecordTest.java
- src/test/java/tutorly/model/attendancerecord/FeedbackTest.java
- src/test/java/tutorly/testutil/AttendanceRecordBuilder.java
- src/test/java/tutorly/testutil/EditSessionDescriptorBuilder.java
> Add feedback command

- src/main/java/tutorly/ui/IconLabel.java
- src/main/java/tutorly/ui/Icons.java
- src/main/java/tutorly/ui/PersonCard.java
- src/main/java/tutorly/ui/PersonListPanel.java
- src/main/java/tutorly/ui/SessionCard.java
- src/main/java/tutorly/ui/SessionListPanel.java
- src/main/resources/view/IconLabel.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/SessionListCard.fxml
> Wrap labels when card selected

- src/main/java/tutorly/logic/parser/AttendanceFeedbackCommandParser.java
- src/main/java/tutorly/logic/parser/AttendanceMarkSessionCommandParser.java
- src/main/java/tutorly/logic/parser/AttendanceUnmarkSessionCommandParser.java
- src/main/java/tutorly/logic/parser/DeleteSessionCommandParser.java
- src/main/java/tutorly/logic/parser/EditSessionCommandParser.java
- src/main/java/tutorly/logic/parser/EnrolSessionCommandParser.java
- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/logic/parser/SearchStudentCommandParser.java
- src/main/java/tutorly/logic/parser/SessionCommandParser.java
- src/main/java/tutorly/logic/parser/UnenrolSessionCommandParser.java
- src/main/java/tutorly/model/person/Identity.java
- src/main/java/tutorly/model/session/Timeslot.java
- src/test/java/tutorly/logic/parser/AttendanceFeedbackCommandParserTest.java
- src/test/java/tutorly/logic/parser/AttendanceMarkSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/AttendanceUnmarkSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/EnrolSessionCommandParserTest.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
- src/test/java/tutorly/logic/parser/UnenrolSessionCommandParserTest.java
> Error message not covering invalid values and format

- docs/UserGuide.md
Fixes emoji in UG to use a valid emoji name
> Fix emoji in UG

- docs/diagrams/DeleteSequenceDiagram.puml
- docs/diagrams/LogicClassDiagram.puml
Update DG diagrams to align with updated design
> Update DG pumls

- src/main/resources/view/MainWindow.fxml
> Increase minWidth of main window

- src/main/java/tutorly/logic/commands/ClearCommand.java
- src/test/java/tutorly/logic/commands/ClearCommandTest.java
> Implement undo for clear command

- docs/UserGuide.md
Closes #302
Closes #315
Closes #344
> Update UG based on consult feedback

- src/main/java/tutorly/storage/JsonAdaptedSession.java
- src/test/java/tutorly/storage/JsonAdaptedSessionTest.java
> Handle invalid timeslots in json data

- src/main/java/tutorly/model/person/Email.java
- src/main/java/tutorly/model/person/Name.java
- src/main/java/tutorly/model/person/Phone.java
- src/main/java/tutorly/model/tag/Tag.java
- src/test/java/tutorly/model/person/EmailTest.java
- src/test/java/tutorly/model/person/NameTest.java
> Fix constraint messages of name, phone, tag, and email

- docs/DeveloperGuide.md
- docs/UserGuide.md
Closes #309
Closes #312
Closes #318
> Add planned search improvements to UG and DG

- src/main/java/tutorly/logic/parser/ParserUtil.java
- src/main/java/tutorly/model/session/Timeslot.java
- src/test/java/tutorly/logic/parser/ParserUtilTest.java
- src/test/java/tutorly/model/session/TimeslotTest.java
> Modify timeslots to only allow end time to be after start time

- src/main/java/tutorly/logic/commands/StudentCommand.java
- src/main/java/tutorly/logic/commands/ViewStudentCommand.java
- src/main/java/tutorly/logic/parser/StudentCommandParser.java
- src/main/java/tutorly/logic/parser/ViewStudentCommandParser.java
- src/test/java/tutorly/logic/commands/StudentCommandTest.java
- src/test/java/tutorly/logic/commands/ViewStudentCommandTest.java
> Add view student command
